### ISSUE TITLE
How to update/upgrade ?

### ISSUE THREAD

**Issue by oviliz** [scaleway-community/scaleway-gogs#12]
Hi guys, what's are the steps to update/upgrade when a new Gogs version would be released?

**Comment by QuentinPerez** [comment]
Hi @oviliz,

I released the latest version 😊, now you can start the version 9.13 of gogs

**Comment by oviliz** [comment]
Hi @QuentinPerez , thanks for your reply.
So, if I'm using an old version image, what do I need to do in order to update the Gogs install?

**Comment by QuentinPerez** [comment]
You can try the following commands:

```console
$ supervisorctl stop gogs
$ cd /go/src/github.com/gogits/gogs
$ git pull
$ git checkout VERSION
$ go build .
$ supervisorctl start gogs
```

**Comment by oviliz** [comment]
Unfortunatelly doesn't work...

`$:/go/src/github.com/gogits/gogs# git checkout VERSION
error: pathspec 'VERSION' did not match any file(s) known to git.
$:/go/src/github.com/gogits/gogs# go build .
# github.com/gogits/gogs/routers/api/v1/convert
routers/api/v1/convert/convert.go:200: undefined: gogs.Team
routers/api/v1/convert/convert.go:201: undefined: gogs.Team
$:/go/src/github.com/gogits/gogs# supervisorctl start gogs
gogs: ERROR (abnormal termination)`

**Comment by QuentinPerez** [comment]
You must replace VERSION by a valid version that you can found [here](https://github.com/gogits/gogs/releases) e.g v0.9.13

**Comment by oviliz** [comment]
Oh... I'm sleeping. But what about you? Are you a GitHub bot?

Thank you. :)
