### ISSUE TITLE
Typo in pricing

### ISSUE THREAD

**Issue by Gedrovits** [scaleway-community/scaleway-gogs#9]
https://www.scaleway.com/imagehub/gogs/

![screen shot 2016-03-29 at 11 26 23](https://cloud.githubusercontent.com/assets/2951943/14102196/c1d65386-f5a1-11e5-97eb-c2ebb80218b3.png)

On first block there is GBM instead of GB.

Posted here, because there is no contact email found on site and don't want to register for the 'community'.

**Comment by oviliz** [comment]
This appears to be fixed by now even not directly related to the Image.

**Comment by Gedrovits** [comment]
@oviliz then this can be closed.
